name: trivy-iac-scan
on:
  push:
    branches:
      - main
  pull_request:
jobs:
  scan:
    name: Scan
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 1
      - name: Run Trivy iac scanner 
        uses: aquasecurity/trivy-action@0.24.0
        with:
          scan-type: 'repo'
          scanners: 'config'
          format: 'sarif'          
          output: 'trivy-iac-results.sarif'
          ignore-unfixed: true

      - name: Upload Trivy artifact
        uses: actions/upload-artifact@v4
        with:
          name: trivy-iac-results.sarif
          path: trivy-iac-results.sarif
